EBAY_ROOT = "/Users/saish/Documents/data/ebay-comp-2024"
OPTIMISED_FILES = "/Users/saish/Documents/data/ebay-comp-2024/optimised_files"
EBAY_ROOT_HPC = "/home/017534556/data/ebay"
OPTIMISED_FILES_HPC = "/home/017534556/data/ebay/optimised_files"

BLACKLIST = [
    "return",
    # "ship",
    "warranty",
    "contact us",  # "Eg: Ignition contact set"
    "handling",
    "faq",
    "privacy",
    "terms",
    "policy",
    "site",
    "home",
    "search",
    "refund",
    "warning",
    "footer" "guarantee",
    "damage",
    "help",
    "about us",
    "delivery",
    "welcome",
    "please",
    "order",
    "payment",
    "business",
    "day",
    "thank",
    "address",
    "distributors",
    "picture",
    "buy",
    "money",
    # "note",
    "download",
    "reserved",
    "copyright",
    # "service",
    "page",
    "email",
    "template",
    "rating",
    # "view", # Interfering with review the notes section or compatibility table
    "reliability",
    "html",
    "div",
    "span",
    "img",
    "trust",
    "rely",
    "feedback",
    "purchase",
    "customer",
    "reason",
    "troubleshooting",
    "powered by",
    "tips",
    "inconvenience",
    "cancer",
    "harm",
    "click",
    "add to" "sorry",
    "comment",
]

SPECIAL_CHARACTERS = [
    ",",
    ".",
    "!",
    "?",
    "-",
    "/",
    ":",
    ";",
    "(",
    ")",
    "[",
    "]",
    "{",
    "}",
    "<",
    ">",
    "|",
    "\\",
    '"',
    "'",
]
